//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Runtime.InteropServices;
using System.Windows;

[assembly: AssemblyTitle("MahTweets Theme Pack")]
[assembly: AssemblyCompany("MahApps")]
[assembly: AssemblyProduct("MahApps")]
[assembly: AssemblyCopyright("Copyright © MahApps 2010")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("2.9.99.901")]
[assembly: AssemblyFileVersion("2.9.99.901")]
[assembly: ThemeInfo(
    ResourceDictionaryLocation.None,
    ResourceDictionaryLocation.SourceAssembly
    )]