//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("MahTweets")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("3.6.0.1")]
[assembly: AssemblyFileVersion("3.6.0.1")]